apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-medusa
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Release.Name }}.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-medusa
                port:
                  number: 80
