apiVersion: v2
name: wc-store
description: WooCommerce Store Chart
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: wordpress
    version: 24.1.1
    repository: https://charts.bitnami.com/bitnami
